### ISSUE TITLE
transitions (testcase: tmp_clafertransitions02.cfr)

### ISSUE THREAD

**Issue by RaoMukkamala** [juodaspaulius/clafer#10]
The following model fails to compile.

`a`
&nbsp;&nbsp;`xor b ?`
&nbsp;&nbsp;&nbsp;&nbsp;`c -->> d`
&nbsp;&nbsp;&nbsp;&nbsp;`d`

`assert[a.b.c => F a.b.d]`

The error message:
Compile error at line 8 column 23...
Name resolver: 'd' not found within paths:c0_a.c0_b
in context of '"c0_b"'
[Finished in 0.0s with exit code 1]
[cmd: ['/home/clafertools/.config/sublime-text-3/Packages/Clafer Tools/clafer', '/home/clafertools/behavioral-0.4.0/clafer/test/positive/tmp_clafertransitions02.cfr', '-m=alloyltl', '-m=clafer', '-m=html', '--add-comments', '--self-contained']]
[dir: /home/clafertools/behavioral-0.4.0/clafer/test/positive]

**Comment by mantkiew** [comment]
this now compiles without error. Added the assertion to the test case.
